#!/bin/bash

#SBATCH --output=%x.%j.out

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
REPO_DIR="$SCRIPT_DIR/.."

# Setup python virtual environment
if [ -x "$(command -v module)" ]; then
    module load lang/python/cpython_3.10.11_gcc122
fi
source $REPO_DIR/.venv/bin/activate
TARGET="$REPO_DIR/examples/linsys_batches.py"

# Run script
python -u $TARGET $@
